### ISSUE TITLE
Getting error while updating django version from 3.2 to 4.2.4

### ISSUE THREAD

**Issue by sauravfouzdar** [jazzband/django-hosts#161]
I have a Django project running with 3.2 , I tried updating the django to latest version with LTS django 4.2.4. I am getting following error while trying to run my project using python manage.py runserver

`Watching for file changes with StatReloader
Performing system checks...

Traceback (most recent call last):
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\utils.py", line 69, in __getitem__
    return self._engines[alias]
           ~~~~~~~~~~~~~^^^^^^^
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\backends\django.py", line 128, in get_package_libraries
    module = import_module(entry[1])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\rest_framework\templatetags\rest_framework.py", line 12, in <module>
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    from rest_framework.renderers import HTMLFormRenderer
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\rest_framework\renderers.py", line 17, in <module>
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Admin\projects\breatheesg\esg_backend\esg_backend\urls.py", line 24, in <module>
    path('api/v1/', include("user.urls", namespace="user-app")),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Admin\projects\breatheesg\esg_backend\user\urls.py", line 15, in <module>
    from .views import (
  File "C:\Users\Admin\projects\breatheesg\esg_backend\user\views.py", line 29, in <module>
    from rest_framework import status, generics, serializers
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\rest_framework\generics.py", line 9, in <module>
    from django.http.multipartparser import parse_header
    from rest_framework import mixins, views
ImportError: cannot import name 'parse_header' from 'django.http.multipartparser' (C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\http\multipartparser.py)

The above exception was the direct cause of the following exception:
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\rest_framework\views.py", line 15, in <module>

Traceback (most recent call last):
  File "C:\Users\Admin\projects\breatheesg\esg_backend\manage.py", line 22, in <module>
    from rest_framework.request import Request
    main()
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\rest_framework\request.py", line 17, in <module>
  File "C:\Users\Admin\projects\breatheesg\esg_backend\manage.py", line 18, in main
    from django.http.multipartparser import parse_header
    execute_from_command_line(sys.argv)
ImportError: cannot import name 'parse_header' from 'django.http.multipartparser' (C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\http\multipartparser.py)
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\core\management\base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\core\management\commands\runserver.py", line 74, in execute
    super().execute(*args, **options)
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\core\management\base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\core\management\commands\runserver.py", line 111, in handle
    self.run(**options)
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\core\management\commands\runserver.py", line 118, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\utils\autoreload.py", line 671, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\utils\autoreload.py", line 660, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\utils\autoreload.py", line 343, in run
    autoreload_started.send(sender=self)
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
           ^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\autoreload.py", line 43, in watch_for_template_changes
    for directory in get_template_directories():
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\autoreload.py", line 16, in get_template_directories
    for backend in engines.all():
                   ^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\utils.py", line 94, in all
    return [self[alias] for alias in self]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\utils.py", line 94, in <listcomp>
    return [self[alias] for alias in self]
            ~~~~^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\utils.py", line 85, in __getitem__
    engine = engine_cls(params)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\backends\django.py", line 24, in __init__
    options["libraries"] = self.get_templatetag_libraries(libraries)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\backends\django.py", line 42, in get_templatetag_libraries
    libraries = get_installed_libraries()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\backends\django.py", line 116, in get_installed_libraries
    return {
           ^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\backends\django.py", line 116, in <dictcomp>
    return {
           ^
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\backends\django.py", line 105, in get_template_tag_modules
    for name in get_package_libraries(pkg):
  File "C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\template\backends\django.py", line 130, in get_package_libraries
    raise InvalidTemplateLibrary(
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'rest_framework.templatetags.rest_framework': cannot import name 'parse_header' from 'django.http.multipartparser' (C:\Users\Admin\Envs\venvdev\Lib\site-packages\django\http\multipartparser.py)`

**Comment by sauravfouzdar** [comment]
not resolved
